name: RealWorldSync
version: '${version}'
main: gq.bxteam.realworldsync.RealWorldSync
api-version: '1.16'
load: POSTWORLD
softdepend: [ PlaceholderAPI ]
authors: [ NONPLAYT ]
description: Synchronizes time and weather from the real world to the game
website: https://modrinth.com/plugin/rws
commands:
  rws:
    aliases: [rws, realworldsync, timesync]
    description: Main command
permissions:
  rws.user:
    description: Default user commands
    default: true
  rws.admin:
    description: Gives access to admin command
    default: op
