# Builds the project with Gradle and uploads to GitHub artifacts.
name: Java CI with Gradle

on:
  push:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Make Gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.3.1
        with:
          arguments: build
      - name: Upload RealWorldSync
        uses: actions/upload-artifact@v4.3.2
        with:
          name: RealWorldSync Dev Artifacts
          path: "build/libs/RealWorldSync-*.jar"
